---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/5/30 23:03
---
local MaskScreenManager = {}

function MaskScreenManager:Show(screen)
    if not self.goAutoMask then
        self.screen = screen
        ResourcesMgr.GetInstance():LoadAsset("UIAutoMask", handler(self, self.OnloadAccomplish))
    else
        self:AttachEvent(screen)
    end
end

function MaskScreenManager:OnloadAccomplish(go)
    self.goAutoMask = go
    self:AttachEvent(self.screen)
end

function MaskScreenManager:AttachEvent(screen)
    --以防界面当帧打开后又立即关闭,导致screen为null报错
    if not screen or not screen:GetCtrlBase() then
        return
    end
    local go = Object.Instantiate(self.goAutoMask, screen:GetPanelRoot().transform)
    go.transform:SetAsFirstSibling()
    go.name = "UIAutoMask_Created by Mask ScreenManager"
    local btnMask = go:GetComponent(typeof(Button))
    if btnMask then
        btnMask.onClick:AddListener(handler(screen,screen.OnClickMaskArea))
    end
end

return MaskScreenManager