---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huangchao05.
--- DateTime: 2020/6/1 12:33
---
local WelcomeUI = class("Welcome",ScreenBase)

function WelcomeUI:BindAction()
    self:AddOnClickListener(self.uiCtrl.btnTouchArea,handler(self,self.OnOpenMainMenuClick))
end

function WelcomeUI:OnOpenMainMenuClick()
    UIMgr:OpenUI("MainMenuUI")
    self:Close()
end

return WelcomeUI