---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huangchao05.
--- DateTime: 2020/6/1 14:50
---
local ThemeChooserUI = class("ThemeChooserUI",ScreenBase)

function ThemeChooserUI:BindAction()
    self.uiCtrl.btnPrev.onClick:AddListener(handler(self,self.OnPreviousPageClick))
    self.uiCtrl.btnNext.onClick:AddListener(handler(self,self.OnNextPageClick))
    self.uiCtrl.btnJumpTheme.onClick:AddListener(handler(self,self.OnOpenJumpTheme))
end

function ThemeChooserUI:UnBindAction()
    self.uiCtrl.btnPrev.onClick:RemoveListener(handler(self,self.OnPreviousPageClick))
    self.uiCtrl.btnNext.onClick:RemoveListener(handler(self,self.OnNextPageClick))
    self.uiCtrl.btnJumpTheme.onClick:RemoveListener(handler(self,self.OnOpenJumpTheme))
end

function ThemeChooserUI:OnPreviousPageClick()
    
end

function ThemeChooserUI:OnNextPageClick()
    
end

function ThemeChooserUI:OnOpenJumpTheme()
    UIMgr:OpenUI("SelectLevelUI")
end

return ThemeChooserUI