---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/5/30 13:29
---
local GuildCreateSubScreen = class("GuildCreateSubScreen",SubScreenBase)

function GuildCreateSubScreen:Init()
    self.uiCtrl.btnCreate.onClick:AddListener(handler(self,self.OnCreateClick))
    self.uiCtrl.btnClose.onClick:AddListener(handler(self,self.OnCloseClick))
end

function GuildCreateSubScreen:OnCreateClick()
    PlayerData:SetHaveGuild(true)
end

function GuildCreateSubScreen:OnCloseClick()
    UIMgr:CloseUI("GuildScreen")
end

return GuildCreateSubScreen