---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/5/30 16:02
---
local GuildInfoSubScreen = class("GuildInfoSubScreen",SubScreenBase)

function GuildInfoSubScreen:Init()
    self.uiCtrl.btnClose.onClick:AddListener(handler(self,self.OnCloseClick))
    self.uiCtrl.btnJumpTask.onClick:AddListener(handler(self,self.OnOpenTaskClick))
end

function GuildInfoSubScreen:OnCloseClick()
    UIMgr:CloseUI("GuildScreen")
end

function GuildInfoSubScreen:OnOpenTaskClick()
    UIMgr:OpenUI("TaskScreen")
end

return GuildInfoSubScreen