---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/7/3 16:02
---
local GameRunSubScreen = class("GameRunSubScreen",SubScreenBase)

function GameRunSubScreen:Init()
end

function GameRunSubScreen:OnCloseClick()
end

function GameRunSubScreen:OnOpenTaskClick()
end

return GameRunSubScreen