---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/7/3 13:29
---
local GameEditorSubScreen = class("GameEditorSubScreen",SubScreenBase)

function GameEditorSubScreen:Init()
    if not self.data then 
        return
    end
    self.SelectAgencyID = false
    --local levelCfg = self.data
    ResourcesMgr.GetInstance():LoadAsset(UI_RES_PREFIX.."Game/btnOrganItem", handler(self,self.InitEditorAgencyList))
end

function GameEditorSubScreen:BindAction()
    self:AddOnClickListener(self.uiCtrl.btnContentArea,self.OnClickContentArea)
    
end

function GameEditorSubScreen:InitEditorAgencyList(obj)
    if obj then
        CommonUtility:RefreshList(self.uiCtrl.rectListOrganEditor,obj,self.data.Agencys,handler(self,self.ListItemRender))
    else
        log("prefab "..UI_RES_PREFIX.."Game/btnOrganItem 加载失败")
    end
end

function GameEditorSubScreen:ListItemRender(idx,item,AgencyID)
    self:AddOnClickListener(item,handler(self,function ()
        self:OnSelectedAgency(AgencyID)
    end))
end

function GameEditorSubScreen:OnSelectedAgency(AgencyID)
    self.SelectAgencyID = AgencyID
end

function GameEditorSubScreen:OnClickContentArea()
    local sceneUnit = MapSceneManager:GetInstance():CreateSceneUnit(UnitClassTypeEnum.Ball,AgencyID,resPath,Vector3.zero,Quaternion.identity)
end

return GameEditorSubScreen