---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/7/3 13:29
---
local GameEditorSubScreen = class("GameEditorSubScreen",SubScreenBase)

function GameEditorSubScreen:Init()
    if not self.data then 
        return
    end
    self.SelectAgencyID = false
    --local levelCfg = self.data
    ResourcesMgr.GetInstance():LoadAsset(UI_RES_PREFIX.."Game/btnOrganItem", handler(self,self.InitEditorAgencyList))
end

function GameEditorSubScreen:BindAction()
    self:AddOnClickListener(self.uiCtrl.btnContentArea,handler(self,self.OnClickContentArea))
end

function GameEditorSubScreen:InitEditorAgencyList(obj)
    if obj then
        CommonUtility:RefreshList(self.uiCtrl.rectListOrganEditor,obj,self.data.Agencys,handler(self,self.ListItemRender))
    else
        log("prefab "..UI_RES_PREFIX.."Game/btnOrganItem 加载失败")
    end
end

function GameEditorSubScreen:ListItemRender(idx,item,AgencyID)
    local toggle = item:GetComponent(typeof(Toggle))
    self:AddOnValueChangedListener(toggle,handler(self,function (value)
        self:OnSelectedAgency(value,AgencyID)
    end))
end

function GameEditorSubScreen:OnSelectedAgency(value,AgencyID)
    if value then
        self.SelectAgencyID = AgencyID
    end
end

function GameEditorSubScreen:OnClickContentArea()
    if not self.SelectAgencyID then
        return
    end
    local AgencyCfg = GameConfig.AgencysByID[self.SelectAgencyID]
    local touchPosOnScreen = Input.mousePosition;
    touchPosOnScreen.z = 1
    local touchPosInWorld = Camera.main:ScreenToWorldPoint(touchPosOnScreen);
    if AgencyCfg then
        local sceneUnit = MapSceneManager:GetInstance():CreateSceneUnit(UnitClassTypeEnum.Ball,self.SelectAgencyID,AgencyCfg.AgencyResUrl,touchPosInWorld,Quaternion.identity)
    end
end

return GameEditorSubScreen