---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huangchao05.
--- DateTime: 2020/7/13 17:36
---

local Entity = class("Entity")
local EntityRef = require("Entities/EntityRef")

function EntToRef(e)
    --如果e已经是引用，直接返回
    if e ~= nil and e.valid ~= nil then
        return e
    end
    local ref
    if e ~= nil then
        ref = e.ref
    end

    if ref == nil then
        ref = EntityRef.New(e)
        if e ~= nil then
            e.ref = ref
        end
    end
    
    return ref
end

function Entity:ctor()
    
end

return Entity