---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huangchao05.
--- DateTime: 2020/7/13 17:40
---

local EntityRef = {}

local EntityNullRef = {
    valid = false
}

function EntityRef.New(e)
    if e == null then
        return EntityNullRef
    end
    local ref = {}
    
    ref.valid = true
    ref.OnDestroyed = EntityRef.OnDestroyed
    ref.Destroy = function(self)
        local mt = getmetatable(self)
        mt.__index:Destroy()
    end
    ref.DestroyImmediate = function(self)
        local mt = getmetatable(self)
        mt.__index:DestroyImmediate()
    end
end

function EntityRef:OnDestroyed()
    self.valid = false
    setmetatable(self,nil)
end

return EntityRef