---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/5/30 12:57
---
local GuildScreen = class("GuildScreen",ScreenBase)
local GuildInfoSubScreen = require("View/Guild/Sub/GuildInfoSubScreen")
local GuildCreateSubScreen = require("View/Guild/Sub/GuildCreateSubScreen")

function GuildScreen:OnShow()
    --有公会就打开公会详情 没有就打开创建界面
    local haveGuild = PlayerData:HaveGuild()
    --处理子界面的显示隐藏
    self.uiCtrl.subInfo.gameObject:SetActive(haveGuild)
    self.uiCtrl.subCreate.gameObject:SetActive(not haveGuild)

    --处理子界面逻辑初始化
    if haveGuild then
        local mSubInfo = GuildInfoSubScreen.New(self.uiCtrl.subInfo)
    else
        local mSubCreate = GuildCreateSubScreen.New(self.uiCtrl.subCreate)
    end
end

function GuildScreen:BindAction()
    self.uiCtrl:AutoRelease(EventManager.OnGuildCreated:Subscribe(handler(self,self.OnGuildCreated))) --监听公会创建成功事件
end

function GuildScreen:OnGuildCreated(created)
    --这里可以直接从PlayerData拿数据，也可以通过参数传递进来，就看你定义的时候是否给事件定义参数了
     --bCreated = PlayerData.GetInstance().HaveGuild();
    --处理子界面的显示隐藏
    self.uiCtrl.subInfo.gameObject:SetActive(created)
    self.uiCtrl.subCreate.gameObject:SetActive(not created)

    --处理子界面逻辑初始化
    if created then
        local mSubInfo = GuildInfoSubScreen.New(self.uiCtrl.subInfo)
    else
        local mSubCreate = GuildCreateSubScreen.New(self.uiCtrl.subCreate)
    end
    
end

return GuildScreen