---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/8/1 21:37
---
local SystemLodUpdateMgr = class("SystemLodUpdateMgr")
local list = require("list")

function SystemLodUpdateMgr:ctor()
    self.frames = {}
    self.deltaTime = {}
    self.lodUpdateFrame = {1, 3, 10, 20}
    self.lodListArray = {}
    for i = 1, 4 do
        self.lodListArray[i] = list:new()
    end
end

function SystemLodUpdateMgr:UnInit()
    --self.running = false
    self.frames = {}
    self.deltaTime = {}
    self.curItem = {}
    for i = 1, 4 do
        self.lodListArray[i] = list:new()
    end
end

function SystemLodUpdateMgr:OnUpdate(deltaTime)
    BeginSample__Base("systemLodUpdateMgr:OnUpdate")
    for i = 1, 4 do
        local frame = self.lodUpdateFrame[i]
        local lodList = self.lodListArray[i]
        local cnt = lodList.length / frame
        local curCnt = 0
        local iter = lodList:get_iter()
        while iter do
            local item = iter.value
            item:OnLodUpdate(TIME_NOW - item.__lastUpdateTime)
            item.__lastUpdateTime = TIME_NOW
            iter = lodList:move_next()
            curCnt = curCnt + 1
            if curCnt >= cnt then
                break
            end
        end
    end
    EndSample__Base()
end

function SystemLodUpdateMgr:Attach(item, lodLevel)
    if lodLevel == nil then
        lodLevel = 1
    end
    self.lodListArray[lodLevel]:pushnode(item.__listNode)
end

function SystemLodUpdateMgr:Detach(item)
    item.__listNode.list:remove(item.__listNode)
end

function SystemLodUpdateMgr:OnLodLevelChanged(item, toLv)
    if toLv == -1 then
        toLv = 4
    else
        toLv = toLv + 1
    end
    if item.__listNode.list then
        item.__listNode.list:remove(item.__listNode)
    end
    self:Attach(item, toLv)
end

return SystemLodUpdateMgr