---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huangchao05.
--- DateTime: 2020/6/2 10:07
---
local SelectLevelUI = class("SelectLevelUI",ScreenBase)

function SelectLevelUI:OnCreate()
    self.levelsCfg = GameConfig.LevelsByLevelID
end

function SelectLevelUI:BindAction()
    self:AddOnClickListener(self.uiCtrl.btnClose,handler(self,self.Close))
end

function SelectLevelUI:UnBindAction()
end

function SelectLevelUI:OnShow()
    self.uiCtrl.txtTitle.text = self.data.titleName
    ResourcesMgr.GetInstance():LoadAsset(UI_RES_PREFIX.."SelectLevel/btnLevel", handler(self,self.InitLevels))
end

function SelectLevelUI:OnStartGameClick(levelCfg)
    UIMgr:OpenUI("GameScreen",levelCfg)
end

function SelectLevelUI:InitLevels(obj)
    if not self.data then
        return
    end
    CommonUtility:RefreshList(self.uiCtrl.groupLevels.transform,obj,self.data.levels,handler(self,self.ListItemRender))
end

function SelectLevelUI:ListItemRender(idx,item,levelID)
    local levelCfg = GameConfig.LevelsByLevelID[levelID]
    item.transform:Find("Text"):GetComponent(typeof(Text)).text = levelCfg.LevelName
    local btn = item:GetComponent(typeof(Button))
    self:AddOnClickListener(btn,handler(self,function ()
        self:OnStartGameClick(levelCfg)
    end))
    --self.uiCtrl.btnLevels:Add(btn)
end

return SelectLevelUI