---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huangchao05.
--- DateTime: 2020/6/2 10:07
---
local SelectLevelUI = class("SelectLevelUI",ScreenBase)

function SelectLevelUI:OnCreate()
    self.levelsCfg = GameConfig.LevelsByLevelID
end

function SelectLevelUI:BindAction()
    self:AddOnClickListener(self.uiCtrl.btnClose,handler(self,self.Close))
end

function SelectLevelUI:UnBindAction()
end

function SelectLevelUI:OnShow()
    self.uiCtrl.txtTitle.text = self.data.titleName
    ResourcesMgr.GetInstance():LoadAsset(UI_RES_PREFIX.."SelectLevel/btnLevel", handler(self,self.InitLevels))
end

function SelectLevelUI:OnStartGameClick()
    log("开始游戏")
end

function SelectLevelUI:InitLevels(obj)
    if not self.data then
        return
    end
    for _, levelID in ipairs(self.data.levels) do
        local level = self.levelsCfg[levelID]
        local levelItem = Object.Instantiate(obj, self.uiCtrl.groupLevels.transform);
        levelItem.transform.localScale = Vector3.one;
        levelItem.transform:Find("Text"):GetComponent(typeof(Text)).text = level.LevelName
        local btn = levelItem:GetComponent(typeof(Button))
        self:AddOnClickListener(btn,handler(self,self.OnStartGameClick))
        self.uiCtrl.btnLevels:Add(btn)
    end
end

return SelectLevelUI