---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huangchao05.
--- DateTime: 2020/6/2 10:07
---
local SelectLevelUI = class("SelectLevelUI",ScreenBase)

function SelectLevelUI:OnCreate()
    ResourcesMgr.GetInstance():LoadAsset(UI_RES_PREFIX.."SelectLevel/btnLevel", handler(self,self.InitLevels));
end

function SelectLevelUI:UnBindAction()
    --for i = 1, self.uiCtrl.btnLevels.count do
    --    btn.onClick:RemoveListener(handler(self,self.OnStartGameClick))
    --end
end

function SelectLevelUI:OnShow()
    self.uiCtrl.txtTitle.text = "测试主题"
end

function SelectLevelUI:OnStartGameClick()
    log("开始游戏")
end

function SelectLevelUI:InitLevels(obj)
    for i = 1, 5 do
        local levelItem = Object.Instantiate(obj, self.uiCtrl.groupLevels.transform);
        levelItem.transform.localScale = Vector3.one;
        local btn = levelItem:GetComponent(typeof(Button))
        btn.onClick:AddListener(handler(self,self.OnStartGameClick))
        self.uiCtrl.btnLevels:Add(btn)
    end
end

return SelectLevelUI