---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huangchao05.
--- DateTime: 2020/6/1 12:30
---
local MainMenuUI = class("MainMenuUI",ScreenBase)

function MainMenuUI:BindAction()
    self.uiCtrl.btnThemeChooser.onClick:AddListener(handler(self,self.OnOpenThemeChooserClick))
    self.uiCtrl.btnCreativeWorkshop.onClick:AddListener(handler(self,self.OnOpenCreativeWorkshopClick))
    self.uiCtrl.btnSetting.onClick:AddListener(handler(self,self.OnOpenSettingClick))
end

function MainMenuUI:UnBindAction()
    self.uiCtrl.btnThemeChooser.onClick:RemoveListener(handler(self,self.OnOpenThemeChooserClick))
    self.uiCtrl.btnCreativeWorkshop.onClick:RemoveListener(handler(self,self.OnOpenCreativeWorkshopClick))
    self.uiCtrl.btnSetting.onClick:RemoveListener(handler(self,self.OnOpenSettingClick))
end

function MainMenuUI:OnOpenThemeChooserClick()
    UIMgr:OpenUI("ThemeChooserUI")
end

function MainMenuUI:OnOpenSettingClick()
    log("--跳设置")
end

function MainMenuUI:OnOpenCreativeWorkshopClick()
    log("跳创意工坊")
end

return MainMenuUI