---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/7/3 12:57
---
local GameScreen = class("GameScreen",ScreenBase)
local GameEditorSubScreen = require("View/Game/Sub/GameEditorSubScreen")
local GameRunSubScreen = require("View/Game/Sub/GameRunSubScreen")

function GameScreen:OnShow()
    local levelCfg = self.data
    local isRunning = false
    --第一次打开就是编辑窗口
    self.uiCtrl.subEditor.gameObject:SetActive(not isRunning)
    self.uiCtrl.subRun.gameObject:SetActive(isRunning)

    --处理子界面逻辑初始化
    if isRunning then
        local _subRun = GameRunSubScreen.New(self.uiCtrl.subRun)
        self:RegisterSubScreen(_subRun)
    else
        local _subEditor = GameEditorSubScreen.New(self.uiCtrl.subEditor,levelCfg)
        self:RegisterSubScreen(_subEditor)
    end
end

function GameScreen:BindAction()
    --self.uiCtrl:AutoRelease(EventManager.OnGuildCreated:Subscribe(handler(self,self.OnGuildCreated))) --监听公会创建成功事件
end

function GameScreen:OnGameRunning()
    --这里可以直接从PlayerData拿数据，也可以通过参数传递进来，就看你定义的时候是否给事件定义参数了
     --bCreated = PlayerData.GetInstance().HaveGuild();
    --处理子界面的显示隐藏
    --self.uiCtrl.subInfo.gameObject:SetActive(created)
    --self.uiCtrl.subCreate.gameObject:SetActive(not created)
    --
    ----处理子界面逻辑初始化
    --if created then
    --    local mSubInfo = GuildInfoSubScreen.New(self.uiCtrl.subInfo)
    --else
    --    local mSubCreate = GuildCreateSubScreen.New(self.uiCtrl.subCreate)
    --end
end

return GameScreen