-------------UnityEngine----
SystemAction = CS.System.Action
Object = CS.UnityEngine.Object;
GameObject = CS.UnityEngine.GameObject;
Transform = CS.UnityEngine.Transform;
ParticleSystem = CS.UnityEngine.ParticleSystem;
Camera = CS.UnityEngine.Camera;
Animator = CS.UnityEngine.Animator;
Space = CS.UnityEngine.Space
CameraClearFlags = CS.UnityEngine.CameraClearFlags;
Shader = CS.UnityEngine.Shader;
Renderer = CS.UnityEngine.Renderer;
TrailRenderer = CS.UnityEngine.TrailRenderer;
Color = CS.UnityEngine.Color;
MeshRenderer = CS.UnityEngine.MeshRenderer;
MeshFilter = CS.UnityEngine.MeshFilter;
SkinnedMeshRenderer = CS.UnityEngine.SkinnedMeshRenderer;
Physics = CS.UnityEngine.Physics;
Ray = CS.UnityEngine.Ray;
Application = CS.UnityEngine.Application;
RuntimePlatform = CS.UnityEngine.RuntimePlatform;
Screen = CS.UnityEngine.Screen;
Input=CS.UnityEngine.Input;
Rect = CS.UnityEngine.Rect;
MaterialPropertyBlock = CS.UnityEngine.MaterialPropertyBlock
Material = CS.UnityEngine.Material
ChatUBBParser = ChatUBBParser;
RenderMode = CS.UnityEngine.RenderMode;
SceneManager = CS.UnityEngine.SceneManagement.SceneManager
Time = CS.UnityEngine.Time
AnimatorStateInfo = CS.UnityEngine.AnimatorStateInfo
Texture2D = CS.UnityEngine.Texture2D
AnimationCurve=CS.UnityEngine.AnimationCurve
Keyframe=CS.UnityEngine.Keyframe
QualitySettings = CS.UnityEngine.QualitySettings
ShadowQuality = CS.UnityEngine.ShadowQuality
Gizmos = CS.UnityEngine.Gizmos
BlendMode = CS.UnityEngine.Rendering.BlendMode
RenderQueue = CS.UnityEngine.Rendering.RenderQueue
PlayableDirector = CS.UnityEngine.Playables.PlayableDirector
SystemInfo = CS.UnityEngine.SystemInfo
Resources =  CS.UnityEngine.Resources
Quaternion =  CS.UnityEngine.Quaternion
Vector3 =  CS.UnityEngine.Vector3
----------------Diy---------------------
GameUIManager = CS.GameUIManager
LuaHelper = CS.LuaHelper
ResourcesMgr = CS.ResourcesMgr
EventManager = CS.EventManager

-----------------UI----------------------
Canvas = CS.UnityEngine.Canvas
Button = CS.UnityEngine.UI.Button
Text = CS.UnityEngine.UI.Text
UICtrlBase = CS.UICtrlBase
ESceenPriority = CS.ESceenPriority
EUICareAboutMoneyType = CS.EUICareAboutMoneyType
PointerEventData = CS.UnityEngine.EventSystems.PointerEventData
EventSystem = CS.UnityEngine.EventSystems.EventSystem
RaycastResult = CS.UnityEngine.EventSystems.RaycastResult