-- Generated by github.com/davyxu/tabtoy
-- Version: 2.9.3

local tab = {
	ThemeChooser = {
		{ index = 1, ThemeName = "这波我无敌", IconUrl = "url", levels = { 1, 2, 3, 4, 5 } 	},
		{ index = 2, ThemeName = "这波我真棒", IconUrl = "url", levels = { 6, 7, 8, 9, 10 } 	},
		{ index = 3, ThemeName = "这波我不行", IconUrl = "url", levels = { 11, 12, 13, 14, 15 } 	}
	}, 

	Levels = {
		{ LevelID = 1, ownerIndex = 1, IconUrl = "url", LevelName = "第1关" 	},
		{ LevelID = 2, ownerIndex = 1, IconUrl = "url", LevelName = "第2关" 	},
		{ LevelID = 3, ownerIndex = 1, IconUrl = "url", LevelName = "第3关" 	},
		{ LevelID = 4, ownerIndex = 1, IconUrl = "url", LevelName = "第4关" 	},
		{ LevelID = 5, ownerIndex = 1, IconUrl = "url", LevelName = "第5关" 	},
		{ LevelID = 6, ownerIndex = 2, IconUrl = "url", LevelName = "第6关" 	},
		{ LevelID = 7, ownerIndex = 2, IconUrl = "url", LevelName = "第7关" 	},
		{ LevelID = 8, ownerIndex = 2, IconUrl = "url", LevelName = "第8关" 	},
		{ LevelID = 9, ownerIndex = 2, IconUrl = "url", LevelName = "第9关" 	},
		{ LevelID = 10, ownerIndex = 2, IconUrl = "url", LevelName = "第10关" 	},
		{ LevelID = 11, ownerIndex = 3, IconUrl = "url", LevelName = "第11关" 	},
		{ LevelID = 12, ownerIndex = 3, IconUrl = "url", LevelName = "第12关" 	},
		{ LevelID = 13, ownerIndex = 3, IconUrl = "url", LevelName = "第13关" 	},
		{ LevelID = 14, ownerIndex = 3, IconUrl = "url", LevelName = "第14关" 	},
		{ LevelID = 15, ownerIndex = 3, IconUrl = "url", LevelName = "第15关" 	}
	}

}


-- index
tab.ThemeChooserByindex = {}
for _, rec in pairs(tab.ThemeChooser) do
	tab.ThemeChooserByindex[rec.index] = rec
end

-- LevelID
tab.LevelsByLevelID = {}
for _, rec in pairs(tab.Levels) do
	tab.LevelsByLevelID[rec.LevelID] = rec
end

-- ownerIndex
tab.LevelsByownerIndex = {}
for _, rec in pairs(tab.Levels) do
	tab.LevelsByownerIndex[rec.ownerIndex] = rec
end

tab.Enum = {
}

return tab