---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by huangchao05.
--- DateTime: 2020/7/9 17:25
---
UnitClassTypeEnum = {
    Ball = 1,--球
    Static = 2,--静态机关
    Dynamic = 3,--动态机关
}
