---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/5/30 16:34
---
local PlayerData = class("PlayerData")

function PlayerData:ctor()
    self.mBHasGuild = false
end

function PlayerData:HaveGuild()
    return self.mBHasGuild
end

function PlayerData:SetHaveGuild(bHaveGuild)
    self.mBHasGuild = bHaveGuild
    EventManager.OnGuildCreated:BroadCastEvent(bHaveGuild)
end

return PlayerData