---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/5/29 22:10
---
return {
    --["MainCityScreen"] =  {uiResPath="MainCity",uiName="MainCityScreen",luaPath = "View/MainCity/MainCityScreen"},
    --["GuildScreen"] =  {uiResPath="Guild",uiName="GuildScreen",luaPath = "View/Guild/GuildScreen"},--工会
    --["TaskScreen"] =  {uiResPath="Task",uiName="TaskScreen",luaPath = "View/Task/TaskScreen"},--工会
    ["WelcomeUI"] = {uiResPath="Welcome",uiName="WelcomeUI",luaPath = "View/Welcome/WelcomeUI"}, --欢迎页
    ["MainMenuUI"] = {uiResPath="MainMenu",uiName="MainMenuUI",luaPath = "View/MainMenu/MainMenuUI"}, --主菜单
    ["ThemeChooserUI"] = {uiResPath="ThemeChooser",uiName="ThemeChooserUI",luaPath = "View/ThemeChooser/ThemeChooserUI"}, --一级选关
    ["SelectLevelUI"] = {uiResPath="SelectLevel/SelectLevel",uiName="SelectLevelUI",luaPath = "View/SelectLevel/SelectLevelUI"}, --二级选关
}
