---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/5/29 22:10
---
return {
    ["LoginScreen"] = {uiResPath="LoginScreen",uiName="LoginScreen",luaPath = "View/Login/LoginScreen"}, --登陆
    ["MainCityScreen"] =  {uiResPath="MainCity",uiName="MainCityScreen",luaPath = "View/MainCity/MainCityScreen"},
    ["GuildScreen"] =  {uiResPath="Guild",uiName="GuildScreen",luaPath = "View/Guild/GuildScreen"},--工会
    ["TaskScreen"] =  {uiResPath="Task",uiName="TaskScreen",luaPath = "View/Task/TaskScreen"},--工会
}
