---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/5/30 13:11
---
local SubScreenBase = class("SubScreenBase")

function SubScreenBase:ctor(subCtrl,param)
    self.uiCtrl = subCtrl
    self.data = param
    self:Init()
end

-----------------子页面复写方法-----------------
function SubScreenBase:OnInit() end

function SubScreenBase:OnDispose() end


return SubScreenBase