---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 54237.
--- DateTime: 2020/5/30 10:31
---
local MainCityScreen = class("MainCityScreen",ScreenBase)

function MainCityScreen:BindAction()
    self.uiCtrl.btnGuild.onClick:AddListener(handler(self,self.OnGuildClick))
    self.uiCtrl.btnTask.onClick:AddListener(handler(self,self.OnTaskClick))
end

function MainCityScreen:UnBindAction()
end

function MainCityScreen:OnShow()
    self.uiCtrl.txtLv.text = 20
end

function MainCityScreen:OnGuildClick()
    UIMgr:OpenUI("GuildScreen")
end

function MainCityScreen:OnTaskClick()
    UIMgr:OpenUI("TaskScreen")
end

function MainCityScreen:UIAdapt(width,height)
    log(string.format("分辨率发生了变化，宽为%s,高为%s", width, height))
end


return MainCityScreen